### ISSUE TITLE
SPAnnularPlate.m

### ISSUE THREAD

**Issue by Batmanabcdefg** [SIMOGroup/SIMO-Package#1]
0.8345  Assembling the system
1.911  Imposing essential boundary conditions
**Error using horzcat
The following error occurred converting from double to struct:
Conversion to struct from double is not possible.

Error in SPAnnularPlate (line 94)
coupledNodes1 = [cp3 cp1; cp1 cp2];**

**Comment by SIMOGroup** [comment]
This error has been fixed, thanks for your finding.

**Comment by Batmanabcdefg** [comment]
thank you .:)
