### ISSUE TITLE
SPSolidCylind.m

### ISSUE THREAD

**Issue by Batmanabcdefg** [SIMOGroup/SIMO-Package#2]
**Error using applyNewmannBdryVals>getNewmannBdryData (line 126)
Data must be stored in column-vector format

Error in applyNewmannBdryVals (line 74)
        [GIdcs, GVals, GDofs] = getNewmannBdryData(NURBS, Mesh, iSide, g,
        LAB, GIdcs, GVals, GDofs, varargin{:});

Error in SPSolidCylind (line 70)
[Press, PressDofs] = applyNewmannBdryVals(Volu, Mesh, press, 3, 'PRES');**

**Comment by SIMOGroup** [comment]
This error has been fixed, thanks for your finding.

**Comment by Batmanabcdefg** [comment]
thank you .:)
