### ISSUE TITLE
\SIMO-Package-master\Modules\GradientElasticity\Thick-Cylindrical

### ISSUE THREAD

**Issue by Batmanabcdefg** [SIMOGroup/SIMO-Package#5]
in  file SPThickWalledCylindGrad.m

ERROR.

0.11503  Assembling the system
0.1246  Imposing natural boundary conditions
0.17556  Imposing essential boundary conditions
0.17973  Solving the system
**Error using calErrorNorm2D
Too many input arguments.
Error in SPThickWalledCylindGrad (line 111)
[DNorm, HNorm, ENorm] = calErrorNorm2D(Mesh, Surf, E, nu, d, solu);**

**Comment by OVGULIU** [comment]
Hello!

is SIMO-Package still under development?

Best regards!
